#line 2 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
static yyconst short int yy_acclist[573] =
    {   0,
       98,   98,  101,   98,   99,  100,   96,   99,  100,   97,
      100,   26,   99,  100,   99,  100,   98,   99,  100,   99,
      100,   21,   99,  100,   23,   99,  100,   34,   99,  100,
       35,   99,  100,   19,   99,  100,   17,   99,  100,   36,
       99,  100,   18,   99,  100,   20,   99,  100,   38,   99,
      100,   37,   99,  100,   28,   99,  100,   27,   99,  100,
       29,   99,  100,   39,   99,  100,   93,   98,   99,  100,
       32,   99,  100,   33,   99,  100,   22,   99,  100,   93,
       98,   99,  100,   93,   98,   99,  100,   93,   98,   99,
      100,   93,   98,   99,  100,   93,   98,   99,  100,   93,

       98,   99,  100,   93,   98,   99,  100,   93,   98,   99,
      100,   93,   98,   99,  100,   93,   98,   99,  100,   93,
       98,   99,  100,   93,   98,   99,  100,   93,   98,   99,
      100,   93,   98,   99,  100,   93,   98,   99,  100,   93,
       98,   99,  100,   30,   99,  100,   24,   99,  100,   31,
       99,  100,   25,   99,  100,    2,    3,  100,    3,  100,
        6,    8,  100,    7,  100,    8,  100,   11,   13,  100,
       12,  100,   13,  100,   98,   54,   94,   15,   98,   16,
       98,   16,   98,    4,   45,   57,   47,   43,   59,   41,
       60,   42,    9,   44,   40,   49,   55,   53,   56,   50,

       93,   98,   46,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   48,   58,    2,    6,    5,   11,   10,   15,   98,
       15,   16,   98,   14,   51,   52,   93,   98,   93,   98,
       93,   98,   93,   98,   93,   98,   93,   98,   93,   98,
       93,   98,   93,   98,   93,   98,   93,   98,   84,   93,

       98,   66,   93,   98,   93,   98,   93,   98,   93,   98,
       93,   98,   93,   98,   93,   98,   85,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   16,
       98,   93,   98,   61,   93,   98,   93,   98,   62,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   75,
       93,   98,   93,   98,   93,   98,   65,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   95,   93,   98,   93,   98,   71,   93,

       98,   93,   98,   16,   98,   93,   98,   93,   98,   76,
       93,   98,   80,   93,   98,   93,   98,   93,   98,   93,
       98,   69,   93,   98,   93,   98,   93,   98,   93,   98,
       93,   98,   93,   98,   64,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   93,   98,   93,
       98,   93,   98,   93,   98,   93,   98,   16,   98,   93,
       98,   93,   98,   93,   98,   70,   93,   98,   89,   93,
       98,   93,   98,   87,   93,   98,   88,   93,   98,   93,
       98,   93,   98,   67,   93,   98,   79,   93,   98,   93,
       98,   77,   93,   98,   93,   98,   93,   98,   93,   98,

       93,   98,   93,   98,   93,   98,   16,   98,   93,   98,
       93,   98,   93,   98,   93,   98,   93,   98,   93,   98,
       93,   98,   93,   98,   82,   93,   98,   93,   98,   93,
       98,   78,   93,   98,   63,   93,   98,    1,   73,   93,
       98,   93,   98,   92,   93,   98,   93,   98,   81,   93,
       98,   90,   93,   98,   72,   93,   98,   91,   93,   98,
       83,   93,   98,   68,   93,   98,   86,   93,   98,   74,
       93,   98
    } ;

static yyconst short int yy_accept[272] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    4,
        7,   10,   12,   15,   17,   20,   22,   25,   28,   31,
       34,   37,   40,   43,   46,   49,   52,   55,   58,   61,
       64,   67,   71,   74,   77,   80,   84,   88,   92,   96,
      100,  104,  108,  112,  116,  120,  124,  128,  132,  136,
      140,  144,  147,  150,  153,  156,  159,  161,  164,  166,
      168,  171,  173,  175,  176,  177,  177,  178,  180,  182,
      184,  185,  186,  187,  188,  189,  190,  191,  192,  193,
      194,  194,  195,  196,  197,  198,  199,  200,  201,  203,
      204,  206,  208,  210,  212,  214,  216,  218,  220,  222,

      224,  226,  228,  230,  232,  234,  236,  238,  240,  242,
      244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
      263,  264,  265,  266,  267,  268,  269,  271,  272,  274,
      274,  275,  276,  277,  279,  281,  283,  285,  287,  289,
      291,  293,  295,  297,  299,  302,  305,  307,  309,  311,
      313,  315,  317,  320,  322,  324,  326,  328,  330,  332,
      332,  334,  336,  338,  340,  342,  344,  347,  349,  352,
      354,  356,  358,  360,  363,  365,  367,  370,  372,  374,
      376,  378,  380,  382,  384,  386,  388,  390,  392,  394,
      394,  395,  397,  399,  402,  404,  406,  408,  410,  413,

      416,  418,  420,  422,  425,  427,  429,  431,  433,  435,
      438,  440,  442,  444,  446,  448,  450,  452,  454,  456,
      458,  460,  462,  464,  466,  469,  472,  474,  477,  480,
      482,  484,  487,  490,  492,  495,  497,  499,  501,  503,
      505,  507,  509,  511,  513,  515,  517,  519,  521,  523,
      525,  528,  530,  532,  535,  538,  538,  539,  542,  544,
      547,  549,  552,  555,  558,  561,  564,  567,  570,  573,
      573
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,    1,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   18,   17,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   25,   39,   40,   41,
       42,   43,   25,   44,   45,   46,   47,   48,   49,   50,
       51,   25,   52,   53,   54,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    3,    2,    4,    5,    2,    2,    2,    2,
        2,    6,    2,    2,    2,    2,    1,    1,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    2,    2,    2
    } ;

static yyconst short int yy_base[284] =
    {   0,
        0,    0,   53,   54,   57,   58,   59,   62,  240,    0,
      860,  860,  211,  167,   66,  860,  148,   57,  860,  860,
      146,   55,  860,   54,   66,  142,  860,   59,  137,   61,
      860,   69,  860,  860,  135,   84,   85,   86,   88,   92,
       95,  101,   99,  102,  108,  105,  118,  111,  125,  131,
      135,  860,   98,  860,  860,    0,  860,    0,  860,   93,
        0,  860,  130,    0,  860,  134,  860,  173,  228,  229,
      860,  860,  860,  860,  860,  860,  860,  860,  860,  860,
      126,  860,  860,   99,  860,  860,  860,   77,  148,  860,
      230,  231,  237,  238,  240,  241,  244,  247,  248,  250,

      254,  251,  257,  258,  260,  266,  270,  273,  283,  284,
      285,  286,  304,  307,  313,  311,  314,  321,  327,  860,
      860,    0,    0,  860,    0,  860,    0,    0,  330,   94,
      860,  860,  860,  331,  333,  334,  337,  340,  341,  354,
      347,  351,  348,  362,  157,  159,  360,  364,  368,  370,
      374,  378,  170,  388,  394,  396,  400,  402,  406,   90,
      408,  410,  418,  414,  420,  422,  424,  430,  428,  442,
      448,  449,  451,  452,  458,  459,  468,  469,  470,  472,
      476,  478,  480,  482,  490,  491,  492,  494,  498,   68,
      860,  506,  507,  509,  519,  528,  529,  535,  537,  539,

      543,  545,  546,  547,  554,  555,  556,  563,  564,  565,
      575,  581,  582,  584,  590,  592,  593,  594,  604,  600,
      606,  610,  613,  616,  626,  627,  630,  638,  639,  640,
      647,  648,  649,  650,  658,  660,  662,  664,  666,  668,
      670,  682,  672,  680,  688,  689,  692,  690,  702,  704,
      708,  711,  714,  722,  724,  108,  860,  726,  734,  736,
      738,  740,  748,  749,  750,  751,  752,  758,  759,  860,
      772,  779,  786,  793,  798,  805,  812,  817,  824,  831,
      838,  845,  852
    } ;

static yyconst short int yy_def[284] =
    {   0,
      270,    1,  271,  271,  272,  272,  273,  273,  270,  274,
      270,  270,  270,  275,  276,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  277,  270,  270,  270,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  270,  270,  270,  270,  278,  270,  279,  270,  270,
      280,  270,  270,  274,  270,  275,  270,  270,  276,  276,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      281,  270,  270,  270,  270,  270,  270,  270,  277,  270,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  270,
      270,  278,  279,  270,  280,  270,   68,  282,  276,  281,
      270,  270,  270,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  283,
      277,  277,  277,  277,  276,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  283,
      270,  277,  277,  277,  277,  276,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      276,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  276,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  270,  270,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,    0,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270
    } ;

static yyconst short int yy_nxt[916] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   10,   10,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   32,   36,
       37,   38,   39,   40,   41,   42,   32,   43,   44,   32,
       45,   46,   32,   32,   47,   48,   49,   50,   51,   32,
       32,   52,   53,   54,   55,   57,   57,   57,   57,   59,
       59,   62,   60,   60,   62,   73,   64,   76,   78,   64,
       63,   68,  191,   63,   64,   79,   77,   80,   74,   84,
       85,   81,   87,   88,   64,   64,   64,   82,   64,   64,
       64,   64,   64,   64,  191,   64,  131,   64,  133,   64,

       64,   64,   64,   70,   64,   64,   64,   64,   64,  256,
       64,   64,  257,   64,   91,   93,   64,   71,   64,  120,
      132,   97,   94,   64,   95,   64,   92,   96,  131,   98,
       64,   64,   99,  101,  102,   64,   64,  105,   67,  103,
       64,  100,  115,  104,  113,  126,  124,  107,   64,  106,
      121,  109,  108,   64,  110,  111,   90,   64,   86,   64,
       83,  114,   64,  112,   64,  116,  119,   75,  117,   72,
       64,   67,  118,  127,  128,   64,  128,  128,  127,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  127,
      127,  128,  128,  128,  128,  128,  128,  127,  128,  128,

      128,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  128,  128,  128,  128,   64,   64,
       64,   64,   65,   64,   64,   64,   64,   64,   64,  270,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,  270,   64,   64,  270,   64,   64,  137,  129,  138,
       64,   64,  135,   64,  134,   64,  270,  136,   64,  270,
      270,  139,  140,   64,   64,   64,   64,  270,   64,   64,
       64,   64,  143,  141,  142,  144,  145,  149,  147,  148,

      270,  270,  146,  151,   64,  150,  152,   64,  270,   64,
      270,   64,   64,   64,   64,  156,   64,  160,   64,   64,
      155,   64,  270,  270,  270,  154,   64,   64,  153,  157,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,  158,  270,   64,   64,   64,   64,  159,
      270,   64,   64,   64,   64,  161,   64,  162,  163,   64,
       64,  270,   64,  164,   64,   64,  168,   64,   64,   64,
       64,  167,  165,   64,   64,   64,  166,  173,   64,   64,
      169,  270,  270,   64,  170,  171,  270,  172,   64,  175,
      174,  176,  270,   64,   64,  177,   64,  178,  270,   64,

       64,   64,   64,  180,  270,   64,   64,   64,   64,  179,
       64,   64,  270,   64,   64,   64,  270,  181,   64,   64,
       64,  182,   64,   64,   64,   64,  270,   64,   64,   64,
       64,  183,  270,   64,  184,   64,  270,  186,  270,  189,
      270,  185,   64,  195,  188,  192,  187,   64,   64,   64,
      194,   64,   64,   64,   64,  193,   64,   64,   64,   64,
      270,  196,  270,   64,   64,  197,  270,  198,   64,   64,
       64,  270,   64,   64,   64,   64,   64,   64,   64,  270,
       64,   64,   64,   64,  201,   64,  199,   64,  270,  202,
       64,   64,   64,  200,   64,   64,   64,   64,   64,   64,

      270,  203,  206,   64,  204,  208,   64,   64,  270,   64,
      270,   64,   64,  205,   64,  211,  270,  207,  270,   64,
      270,  209,  270,  214,   64,  210,  270,  212,   64,   64,
      216,  213,  215,   64,   64,   64,  270,   64,  217,   64,
       64,  218,   64,   64,   64,   64,   64,   64,   64,  270,
       64,   64,   64,  219,   64,   64,   64,  270,  222,   64,
       64,   64,  220,   64,   64,   64,  270,  223,   64,   64,
       64,  221,  224,  270,  270,   64,  270,  270,  225,  270,
       64,   64,   64,  270,   64,  229,   64,   64,  228,   64,
       64,  226,   64,   64,   64,   64,  227,   64,   64,   64,

       64,  231,  270,  270,   64,   64,   64,  232,  230,   64,
       64,   64,  233,   64,  270,   64,   64,  234,   64,  236,
      270,   64,  238,  270,  270,  237,   64,   64,  241,  235,
       64,   64,   64,  240,  239,   64,  270,  270,   64,   64,
       64,  243,  244,   64,   64,   64,  270,   64,   64,   64,
       64,  242,   64,   64,   64,   64,  270,  270,   64,  246,
       64,  245,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,  270,   64,  270,   64,  249,  248,
       64,  247,   64,  256,  270,   64,  257,   64,   64,   64,
       64,  270,   64,   64,   64,   64,  251,   64,  270,  253,

      270,  270,   64,  252,   64,  250,  254,   64,   64,   64,
      270,   64,  270,   64,   64,  255,   64,  258,  270,   64,
      261,  260,   64,  263,   64,  259,   64,   64,  270,   64,
      270,   64,  270,  270,   64,  262,   64,  265,   64,   64,
       64,   64,  270,   64,  266,   64,  267,  264,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
      270,  270,  270,   64,   64,  270,  270,  268,  270,  270,
      270,  269,   56,   56,   56,   56,   56,   56,   56,   58,
       58,   58,   58,   58,   58,   58,   61,   61,   61,   61,
       61,   61,   61,   64,  270,  270,  270,   64,   66,   66,

       66,   66,   66,   66,   66,   69,  270,  270,  270,   69,
      270,   69,   89,  270,  270,  270,   89,  122,  122,  270,
      270,  122,  122,  122,  123,  123,  270,  123,  270,  123,
      123,  125,  125,  270,  125,  125,  270,  125,  130,  130,
      130,  130,  130,  130,  130,  128,  128,  270,  128,  128,
      128,  128,  190,  190,  190,  190,  190,  190,  190,    9,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270
    } ;

static yyconst short int yy_chk[916] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,    7,    5,    6,    8,   18,   15,   22,   24,   32,
        7,   15,  190,    8,   32,   24,   22,   25,   18,   28,
       28,   25,   30,   30,   36,   37,   38,   25,   39,   36,
       37,   38,   40,   39,  160,   41,  130,   40,   88,   43,

       41,   42,   44,   15,   43,   46,   42,   44,   45,  256,
       46,   48,  256,   45,   36,   38,   48,   15,   47,   53,
       84,   39,   38,   47,   38,   49,   37,   38,   81,   39,
       49,   50,   40,   41,   42,   51,   50,   45,   66,   43,
       51,   40,   49,   44,   48,   63,   60,   46,   89,   45,
       53,   47,   46,   89,   47,   47,   35,  145,   29,  146,
       26,   48,  145,   47,  146,   49,   51,   21,   50,   17,
      153,   14,   50,   68,   68,  153,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   69,   70,
       91,   92,   13,   69,   70,   91,   92,   93,   94,    9,
       95,   96,   93,   94,   97,   95,   96,   98,   99,   97,
      100,  102,   98,   99,  101,  100,  102,  103,  104,  101,
      105,    0,  103,  104,    0,  105,  106,   94,   70,   95,
      107,  106,   92,  108,   91,  107,    0,   93,  108,   69,
       70,   96,   97,  109,  110,  111,  112,    0,  109,  110,
      111,  112,  100,   98,   99,  101,  102,  106,  104,  105,

        0,    0,  103,  107,  113,  106,  108,  114,    0,  113,
        0,  116,  114,  115,  117,  112,  116,  115,  115,  117,
      111,  118,    0,    0,    0,  110,  118,  119,  109,  112,
      129,  134,  119,  135,  136,  129,  134,  137,  135,  136,
      138,  139,  137,  113,    0,  138,  139,  141,  143,  114,
        0,  142,  141,  143,  140,  116,  142,  117,  118,  140,
      147,    0,  144,  119,  148,  147,  136,  144,  149,  148,
      150,  135,  129,  149,  151,  150,  134,  141,  152,  151,
      137,  129,    0,  152,  138,  139,    0,  140,  154,  143,
      142,  144,    0,  154,  155,  147,  156,  148,    0,  155,

      157,  156,  158,  150,    0,  157,  159,  158,  161,  149,
      162,  159,    0,  161,  164,  162,    0,  151,  163,  164,
      165,  152,  166,  163,  167,  165,    0,  166,  169,  167,
      168,  154,    0,  169,  155,  168,    0,  157,    0,  159,
        0,  156,  170,  164,  158,  161,  157,  170,  171,  172,
      163,  173,  174,  171,  172,  162,  173,  174,  175,  176,
        0,  165,    0,  175,  176,  166,    0,  168,  177,  178,
      179,  165,  180,  177,  178,  179,  181,  180,  182,    0,
      183,  181,  184,  182,  172,  183,  170,  184,    0,  173,
      185,  186,  187,  171,  188,  185,  186,  187,  189,  188,

        0,  175,  179,  189,  176,  181,  192,  193,    0,  194,
        0,  192,  193,  178,  194,  184,    0,  180,    0,  195,
        0,  182,    0,  187,  195,  183,    0,  185,  196,  197,
      189,  186,  188,  196,  197,  198,    0,  199,  189,  200,
      198,  192,  199,  201,  200,  202,  203,  204,  201,    0,
      202,  203,  204,  193,  205,  206,  207,    0,  197,  205,
      206,  207,  195,  208,  209,  210,    0,  198,  208,  209,
      210,  196,  201,    0,    0,  211,    0,    0,  202,  196,
      211,  212,  213,    0,  214,  207,  212,  213,  206,  214,
      215,  203,  216,  217,  218,  215,  205,  216,  217,  218,

      220,  209,    0,    0,  219,  220,  221,  211,  208,  219,
      222,  221,  212,  223,    0,  222,  224,  213,  223,  215,
        0,  224,  217,    0,    0,  216,  225,  226,  220,  214,
      227,  225,  226,  219,  218,  227,    0,    0,  228,  229,
      230,  222,  223,  228,  229,  230,    0,  231,  232,  233,
      234,  221,  231,  232,  233,  234,    0,  221,  235,  227,
      236,  224,  237,  235,  238,  236,  239,  237,  240,  238,
      241,  239,  243,  240,    0,  241,    0,  243,  234,  231,
      244,  230,  242,  242,    0,  244,  242,  242,  245,  246,
      248,    0,  247,  245,  246,  248,  237,  247,    0,  239,

        0,    0,  249,  238,  250,  236,  240,  249,  251,  250,
        0,  252,    0,  251,  253,  241,  252,  243,    0,  253,
      246,  245,  254,  248,  255,  244,  258,  254,    0,  255,
        0,  258,    0,  242,  259,  247,  260,  250,  261,  259,
      262,  260,    0,  261,  252,  262,  253,  249,  263,  264,
      265,  266,  267,  263,  264,  265,  266,  267,  268,  269,
        0,    0,    0,  268,  269,    0,    0,  259,    0,    0,
        0,  261,  271,  271,  271,  271,  271,  271,  271,  272,
      272,  272,  272,  272,  272,  272,  273,  273,  273,  273,
      273,  273,  273,  274,    0,    0,    0,  274,  275,  275,

      275,  275,  275,  275,  275,  276,    0,    0,    0,  276,
        0,  276,  277,    0,    0,    0,  277,  278,  278,    0,
        0,  278,  278,  278,  279,  279,    0,  279,    0,  279,
      279,  280,  280,    0,  280,  280,    0,  280,  281,  281,
      281,  281,  281,  281,  281,  282,  282,    0,  282,  282,
      282,  282,  283,  283,  283,  283,  283,  283,  283,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
#define INITIAL 0
#define IFILE 1
#define CODEBLOCK 2
#define COMMENT 3

#line 5 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
#include <stdlib.h>
#include <string.h>
#include "idlcpp.y.h"
#include "yyfuncs.h"

YY_BUFFER_STATE createBufferState(FILE* file);
int yytokenno = 0;
int yycolumnno = 1;
int yyHasArrayProperty = 0;
int yyHasListProperty = 0;
int yyHasMapProperty = 0;
int yyHasDelegate = 0;
#line 752 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"


#line 906 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 860 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 21 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{BEGIN IFILE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{
						{
							int c;
							while((c = input()) && c != '\n')
							{}
							addSourceFile(yytext);
							yycolumnno = 0;
							BEGIN INITIAL;
						}
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{fprintf(stderr, "%d bad import line\n", yylineno); yyterminate();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN CODEBLOCK;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1; yytokenno++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno++; yytokenno++;}
	YY_BREAK
case YY_STATE_EOF(CODEBLOCK):
#line 39 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{unterminatedCode();yyterminate();}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN COMMENT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += strlen(yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock("\n"); yycolumnno = 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 46 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{unterminatedComment();yyterminate();}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock("\n"); yycolumnno = 1;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 52 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yyterminate();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext + 2); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext + 1); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 17:
#line 59 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 18:
#line 60 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 19:
#line 61 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 20:
#line 62 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 21:
#line 63 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 22:
#line 64 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 23:
#line 65 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 24:
#line 66 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 25:
#line 67 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 26:
#line 68 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 27:
#line 69 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 28:
#line 70 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 29:
#line 71 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 30:
#line 72 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 31:
#line 73 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 32:
#line 74 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 33:
#line 75 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 34:
#line 76 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 35:
#line 77 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 36:
#line 78 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 37:
#line 79 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 38:
#line 80 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 39:
YY_RULE_SETUP
#line 80 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(yytext[0]);				yycolumnno++; yytokenno++; return yytext[0];}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_scope);					yycolumnno += strlen(yytext); yytokenno++; return SCOPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_add_assign);				yycolumnno += strlen(yytext); yytokenno++; return ADD_ASSIGN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_sub_assign);				yycolumnno += strlen(yytext); yytokenno++; return SUB_ASSIGN;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_mul_assign);				yycolumnno += strlen(yytext); yytokenno++; return MUL_ASSIGN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_div_assign);				yycolumnno += strlen(yytext); yytokenno++; return DIV_ASSIGN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_mod_assign);				yycolumnno += strlen(yytext); yytokenno++; return MOD_ASSIGN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_xor_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_XOR_ASSIGN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_and_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_AND_ASSIGN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_or_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_OR_ASSIGN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_left_shift);				yycolumnno += strlen(yytext); yytokenno++; return LEFT_SHIFT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_right_shift);			yycolumnno += strlen(yytext); yytokenno++; return RIGHT_SHIFT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_left_shift_assign);		yycolumnno += strlen(yytext); yytokenno++; return LEFT_SHIFT_ASSIGN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_right_shift_assign);		yycolumnno += strlen(yytext); yytokenno++; return RIGHT_SHIFT_ASSIGN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_equal);					yycolumnno += strlen(yytext); yytokenno++; return EQUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_not_equal);				yycolumnno += strlen(yytext); yytokenno++; return NOT_EQUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_less_equal);				yycolumnno += strlen(yytext); yytokenno++; return LESS_EQUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_greater_equal);			yycolumnno += strlen(yytext); yytokenno++; return GREATER_EQUAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_and);					yycolumnno += strlen(yytext); yytokenno++; return AND;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_or);						yycolumnno += strlen(yytext); yytokenno++; return OR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_inc);					yycolumnno += strlen(yytext); yytokenno++; return INC;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_operator_dec);					yycolumnno += strlen(yytext); yytokenno++; return DEC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_bool);					yycolumnno += strlen(yytext); yytokenno++; return BOOL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_char);					yycolumnno += strlen(yytext); yytokenno++; return CHAR;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_wchar_t);					yycolumnno += strlen(yytext); yytokenno++; return WCHAR_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_short);					yycolumnno += strlen(yytext); yytokenno++; return SHORT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_long);					yycolumnno += strlen(yytext); yytokenno++; return LONG;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_int);						yycolumnno += strlen(yytext); yytokenno++; return INT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_signed);					yycolumnno += strlen(yytext); yytokenno++; return SIGNED;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_unsigned);				yycolumnno += strlen(yytext); yytokenno++; return UNSIGNED;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_float);					yycolumnno += strlen(yytext); yytokenno++; return FLOAT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_double);					yycolumnno += strlen(yytext); yytokenno++; return DOUBLE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_void);					yycolumnno += strlen(yytext); yytokenno++; return VOID;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_string_t);				yycolumnno += strlen(yytext); yytokenno++; return STRING_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_abstract);				yycolumnno += strlen(yytext); yytokenno++; return ABSTRACT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_namespace);				yycolumnno += strlen(yytext); yytokenno++; return NAMESPACE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_enum);					yycolumnno += strlen(yytext); yytokenno++; return ENUM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_class);					yycolumnno += strlen(yytext); yytokenno++; return CLASS;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_struct);					yycolumnno += strlen(yytext); yytokenno++; return STRUCT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_virtual);					yycolumnno += strlen(yytext); yytokenno++; return VIRTUAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_static);					yycolumnno += strlen(yytext); yytokenno++; return STATIC;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_const);					yycolumnno += strlen(yytext); yytokenno++; return CONST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_operator);				yycolumnno += strlen(yytext); yytokenno++; return OPERATOR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_typedef);					yycolumnno += strlen(yytext); yytokenno++; return TYPEDEF;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_typename);				yycolumnno += strlen(yytext); yytokenno++; return TYPENAME;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_get);						yycolumnno += strlen(yytext); yytokenno++; return GET;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_set);						yycolumnno += strlen(yytext); yytokenno++; return SET;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_candidate);				yycolumnno += strlen(yytext); yytokenno++; return CANDIDATE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_nocode);					yycolumnno += strlen(yytext); yytokenno++; return NOCODE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_nometa);					yycolumnno += strlen(yytext); yytokenno++; return NOMETA;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_export);					yycolumnno += strlen(yytext); yytokenno++; return EXPORT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_override);				yycolumnno += strlen(yytext); yytokenno++; return OVERRIDE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_template);				yycolumnno += strlen(yytext); yytokenno++; return TEMPLATE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_delegate);				yycolumnno += strlen(yytext); yytokenno++; return DELEGATE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newIdentify(yytext);					yycolumnno += strlen(yytext); yytokenno++; return IDENTIFY;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 140 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newString(yytext + 1);					yycolumnno += strlen(yytext); yytokenno++; return STRING;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 141 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newString(yytext + 3);					yycolumnno += strlen(yytext); yytokenno++; return U8STRING;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 143 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{++yycolumnno;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 144 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 146 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 147 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 149 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1453 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 270);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 149 "D:\\idlcpp\\idlcpp\\src\\idlcpp.l"


YY_BUFFER_STATE createBufferState(FILE* file)
{
	YY_BUFFER_STATE bs;
	bs = yy_create_buffer(file, YY_BUF_SIZE);
	return bs;
}