#line 2 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[453] =
    {   0,
       62,   62,   65,   62,   63,   64,   60,   63,   64,   61,
       64,   63,   64,   62,   63,   64,   63,   64,   40,   63,
       64,   24,   63,   64,   25,   63,   64,   41,   63,   64,
       17,   63,   64,   63,   64,   19,   63,   64,   18,   63,
       64,   26,   63,   64,   27,   63,   64,   59,   62,   63,
       64,   22,   63,   64,   23,   63,   64,   42,   63,   64,
       59,   62,   63,   64,   59,   62,   63,   64,   59,   62,
       63,   64,   59,   62,   63,   64,   59,   62,   63,   64,
       59,   62,   63,   64,   59,   62,   63,   64,   59,   62,
       63,   64,   59,   62,   63,   64,   59,   62,   63,   64,

       59,   62,   63,   64,   59,   62,   63,   64,   59,   62,
       63,   64,   59,   62,   63,   64,   59,   62,   63,   64,
       59,   62,   63,   64,   59,   62,   63,   64,   20,   63,
       64,   21,   63,   64,    2,    3,   64,    3,   64,    6,
        8,   64,    7,   64,    8,   64,   11,   13,   64,   12,
       64,   13,   64,   62,   62,   15,    4,   16,    9,   28,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,

       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,    2,    6,    5,   11,   10,   62,   15,   14,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   53,   59,
       62,   34,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   54,   59,   62,   59,
       62,   59,   62,   59,   62,   59,   62,   59,   62,   59,
       62,   59,   62,   59,   62,   59,   62,   62,   59,   62,
       29,   59,   62,   30,   59,   62,   59,   62,   59,   62,
       59,   62,   45,   59,   62,   59,   62,   59,   62,   33,

       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   59,   62,   39,   59,   62,   59,
       62,   62,   59,   62,   46,   59,   62,   50,   59,   62,
       59,   62,   59,   62,   37,   59,   62,   59,   62,   59,
       62,   59,   62,   59,   62,   59,   62,   32,   59,   62,
       59,   62,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   59,   62,   62,   59,   62,   38,   59,   62,
       57,   59,   62,   59,   62,   55,   59,   62,   56,   59,
       62,   59,   62,   59,   62,   35,   59,   62,   49,   59,

       62,   47,   59,   62,   59,   62,   59,   62,   59,   62,
       59,   62,   62,   59,   62,   59,   62,   59,   62,   59,
       62,   51,   59,   62,   59,   62,   48,   59,   62,   31,
       59,   62,    1,   43,   59,   62,   59,   62,   58,   59,
       62,   59,   62,   36,   59,   62,   44,   59,   62,   52,
       59,   62
    } ;

static yyconst short int yy_accept[208] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    4,
        7,   10,   12,   14,   17,   19,   22,   25,   28,   31,
       34,   36,   39,   42,   45,   48,   52,   55,   58,   61,
       65,   69,   73,   77,   81,   85,   89,   93,   97,  101,
      105,  109,  113,  117,  121,  125,  129,  132,  135,  138,
      140,  143,  145,  147,  150,  152,  154,  155,  156,  157,
      158,  159,  160,  160,  161,  163,  165,  167,  169,  171,
      173,  175,  177,  179,  181,  183,  185,  187,  189,  191,
      193,  195,  197,  199,  201,  203,  205,  207,  209,  211,
      213,  214,  215,  216,  217,  218,  219,  220,  220,  221,

      223,  225,  227,  229,  231,  233,  235,  237,  239,  242,
      245,  247,  249,  251,  253,  255,  257,  260,  262,  264,
      266,  268,  270,  272,  274,  276,  278,  279,  281,  284,
      287,  289,  291,  293,  296,  298,  300,  303,  305,  307,
      309,  311,  313,  315,  317,  319,  321,  323,  325,  327,
      330,  332,  333,  335,  338,  341,  343,  345,  348,  350,
      352,  354,  356,  358,  361,  363,  365,  367,  369,  371,
      373,  375,  376,  378,  381,  384,  386,  389,  392,  394,
      396,  399,  402,  405,  407,  409,  411,  413,  414,  416,
      418,  420,  422,  425,  427,  430,  433,  433,  434,  437,

      439,  442,  444,  447,  450,  453,  453
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    7,    1,    8,
        9,   10,    1,   11,    1,    1,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
        1,   17,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       19,    1,   20,   21,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   18,   18,   32,   33,   34,
       35,   36,   18,   37,   38,   39,   40,   41,   42,   43,
       44,   18,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    2,    3,    4,    1,    5,    2,    2,    2,    6,
        2,    2,    7,    2,    2,    2,    2,    7,    2,    2,
        2,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    2,    2
    } ;

static yyconst short int yy_base[218] =
    {   0,
        0,    0,   44,   46,   48,   49,   50,   51,  258,    0,
      606,  606,  606,  187,   56,  606,  606,  606,  606,  606,
       45,  181,  606,  606,  606,   62,  606,  606,  606,   63,
       64,   70,   69,   72,   71,   80,   77,   78,   85,   83,
       88,   91,   90,   93,  109,  111,  606,  606,    0,  606,
        0,  606,  174,    0,  606,  165,    0,  134,    0,  606,
       91,  606,  152,  606,  118,  127,  128,  130,  136,  137,
      138,  144,  145,  147,  146,  153,  155,  161,  163,  156,
      168,  169,  171,  174,  186,  185,  192,  197,  200,  199,
        0,    0,  606,    0,  606,   90,    0,  114,  606,  206,

      209,  211,  212,  214,  219,  221,  227,  232,  234,  235,
      237,  246,  248,  255,  256,  258,  263,  264,  266,  269,
      271,  276,  274,  279,  284,  289,   74,  287,  294,  297,
      308,  314,  315,  316,  321,  322,  324,  327,  329,  330,
      335,  332,  337,  340,  343,  355,  338,  349,  361,  370,
      372,   43,  380,  378,  381,  383,  386,  388,  391,  389,
      394,  397,  399,  406,  407,  414,  413,  419,  421,  430,
      429,   17,  431,  436,  439,  442,  444,  449,  456,  457,
      458,  459,  465,  466,  468,  467,  473,  223,  474,  475,
      476,  482,  484,  485,  491,  492,  242,  606,  497,  500,

      503,  505,  513,  514,  515,  606,  532,  539,  546,  553,
      556,  563,  570,  577,  584,  591,  598
    } ;

static yyconst short int yy_def[218] =
    {   0,
      206,    1,  207,  207,  208,  208,  209,  209,  206,  210,
      206,  206,  206,  210,  211,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  212,  206,  206,  206,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  206,  206,  213,  206,
      214,  206,  206,  215,  206,  206,  210,  210,  216,  206,
      211,  206,  217,  206,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      213,  214,  206,  215,  206,  210,  216,  217,  206,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  210,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  210,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  210,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  210,  212,  212,
      212,  212,  212,  212,  212,  212,  206,  206,  212,  212,

      212,  212,  212,  212,  212,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206
    } ;

static yyconst short int yy_nxt[653] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   10,   22,   23,   24,   25,   26,   27,   28,
       29,   26,   30,   31,   32,   33,   34,   35,   36,   26,
       37,   38,   26,   39,   40,   41,   26,   42,   43,   44,
       45,   46,   26,   26,   47,   48,   50,   50,   50,   50,
       52,   52,   55,   55,   62,  188,   63,   53,   53,   56,
       56,   59,   57,   57,   57,   60,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,  172,
       57,   57,   57,   57,   57,   57,   66,   57,   57,   57,
       57,   57,   57,   57,   57,   57,  206,   57,   67,   68,

      206,   69,   74,   71,   70,   72,   75,   78,  152,   57,
       76,   57,   77,   57,   73,   57,   99,   82,   57,   79,
       83,   84,   57,   80,   81,  127,   87,   57,   57,   85,
       57,   57,   57,   86,   57,   90,   57,   57,   57,   88,
       57,   57,   57,   89,   57,   57,   57,   57,   57,   57,
       57,   57,  102,   57,   99,   57,   57,   57,  103,   57,
       57,   57,  101,   57,  100,   57,   96,   57,   57,   57,
      104,   57,   57,   57,   57,   57,   95,  105,   57,   93,
      107,  108,  115,  106,  109,   57,   57,  113,  111,   57,
       57,  110,   57,  112,   64,  114,   57,   57,  116,   57,

       57,   57,  119,   57,   57,  118,   57,  117,  120,   57,
       57,   57,   57,   57,   57,   57,   57,   58,   57,   57,
      122,   57,  121,   57,  197,   57,  198,   57,  126,  123,
      125,   57,   57,  124,   57,   57,   57,   57,   57,   57,
      129,   57,  133,  197,  128,  198,   57,  130,   57,  131,
       57,  132,   57,  134,  136,   57,   57,  206,   57,   57,
       57,  135,   57,   57,   57,  137,   57,   57,   57,   57,
       57,   57,  138,   57,   57,   57,   57,  206,   57,   57,
       57,  140,  139,   57,   57,  206,  206,   57,   57,   57,
      142,   57,  141,   57,   57,  206,  206,   57,   57,  144,

      143,   57,  147,  206,  148,  206,  206,  145,   57,  150,
      146,  151,   57,  206,   57,   57,   57,  149,   57,   57,
       57,   57,   57,  153,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,  154,  156,   57,  206,   57,
      206,  206,  155,   57,  160,   57,  206,  157,  206,   57,
      158,   57,  163,  168,  159,   57,  165,  206,  161,  206,
       57,  162,   57,  166,   57,  164,   57,  169,   57,  167,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,  206,   57,   57,   57,

      170,   57,  173,   57,  206,  206,   57,   57,  171,  174,
       57,   57,  206,   57,   57,  177,  178,   57,   57,   57,
      206,   57,  206,   57,  175,   57,  176,  179,  206,   57,
       57,   57,  181,   57,   57,   57,   57,  180,  182,   57,
       57,  206,   57,   57,   57,  184,   57,  206,   57,   57,
      187,  183,  186,   57,  185,  189,   57,   57,   57,   57,
       57,   57,   57,   57,  190,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,  191,   57,  206,   57,   57,   57,  192,   57,   57,
      206,   57,   57,  193,  194,   57,   57,   57,  195,  200,

       57,   57,  201,   57,   57,   57,  206,   57,  206,   57,
      203,  196,  199,   57,   57,   57,  206,   57,   57,   57,
      206,  206,  202,  206,  206,  206,  204,  206,  206,  206,
      206,  205,   49,   49,   49,   49,   49,   49,   49,   51,
       51,   51,   51,   51,   51,   51,   54,   54,   54,   54,
       54,   54,   54,   57,  206,  206,  206,  206,  206,   57,
       61,   61,   61,   65,  206,  206,  206,  206,  206,   65,
       91,   91,  206,  206,   91,   91,   91,   92,   92,  206,
       92,   92,  206,   92,   94,   94,  206,   94,   94,  206,
       94,   97,   97,  206,   97,   97,   97,   97,   98,   98,

       98,   98,   98,   98,   98,    9,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206
    } ;

static yyconst short int yy_chk[653] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        5,    6,    7,    8,   21,  172,   21,    5,    6,    7,
        8,   15,   26,   30,   31,   15,   26,   30,   31,   33,
       32,   35,   34,   33,   32,   35,   34,   37,   38,  152,
       36,   37,   38,   40,   36,   39,   30,   40,   41,   39,
       43,   42,   41,   44,   43,   42,   61,   44,   31,   32,

       61,   32,   35,   33,   32,   34,   36,   39,  127,   45,
       37,   46,   38,   45,   34,   46,   98,   42,   65,   39,
       42,   42,   65,   40,   41,   96,   44,   66,   67,   42,
       68,   66,   67,   43,   68,   46,   69,   70,   71,   45,
       69,   70,   71,   45,   72,   73,   75,   74,   72,   73,
       75,   74,   68,   76,   63,   77,   80,   76,   69,   77,
       80,   78,   67,   79,   66,   78,   58,   79,   81,   82,
       70,   83,   81,   82,   84,   83,   56,   71,   84,   53,
       73,   74,   80,   72,   75,   86,   85,   79,   77,   86,
       85,   76,   87,   78,   22,   79,   87,   88,   81,   90,

       89,   88,   84,   90,   89,   83,  100,   82,   85,  101,
      100,  102,  103,  101,  104,  102,  103,   14,  104,  105,
       86,  106,   85,  105,  188,  106,  188,  107,   90,   87,
       89,  107,  108,   88,  109,  110,  108,  111,  109,  110,
      101,  111,  105,  197,  100,  197,  112,  102,  113,  103,
      112,  104,  113,  106,  108,  114,  115,    9,  116,  114,
      115,  107,  116,  117,  118,  111,  119,  117,  118,  120,
      119,  121,  112,  120,  123,  121,  122,    0,  123,  124,
      122,  114,  113,  124,  125,    0,    0,  128,  125,  126,
      116,  128,  115,  126,  129,    0,    0,  130,  129,  119,

      118,  130,  122,    0,  123,    0,    0,  120,  131,  125,
      121,  126,  131,    0,  132,  133,  134,  124,  132,  133,
      134,  135,  136,  128,  137,  135,  136,  138,  137,  139,
      140,  138,  142,  139,  140,  141,  142,  143,  147,  141,
      144,  143,  147,  145,  144,  131,  133,  145,    0,  148,
        0,    0,  132,  148,  139,  146,    0,  135,    0,  146,
      136,  149,  142,  147,  138,  149,  144,    0,  140,    0,
      150,  141,  151,  145,  150,  143,  151,  148,  154,  146,
      153,  155,  154,  156,  153,  155,  157,  156,  158,  160,
      157,  159,  158,  160,  161,  159,    0,  162,  161,  163,

      149,  162,  153,  163,    0,    0,  164,  165,  151,  156,
      164,  165,    0,  167,  166,  160,  161,  167,  166,  168,
        0,  169,    0,  168,  157,  169,  159,  162,    0,  171,
      170,  173,  165,  171,  170,  173,  174,  163,  166,  175,
      174,    0,  176,  175,  177,  168,  176,    0,  177,  178,
      171,  167,  170,  178,  169,  173,  179,  180,  181,  182,
      179,  180,  181,  182,  176,  183,  184,  186,  185,  183,
      184,  186,  185,  187,  189,  190,  191,  187,  189,  190,
      191,  179,  192,    0,  193,  194,  192,  180,  193,  194,
        0,  195,  196,  184,  185,  195,  196,  199,  186,  190,

      200,  199,  191,  201,  200,  202,    0,  201,    0,  202,
      194,  187,  189,  203,  204,  205,    0,  203,  204,  205,
        0,    0,  192,    0,    0,    0,  200,    0,    0,    0,
        0,  202,  207,  207,  207,  207,  207,  207,  207,  208,
      208,  208,  208,  208,  208,  208,  209,  209,  209,  209,
      209,  209,  209,  210,    0,    0,    0,    0,    0,  210,
      211,  211,  211,  212,    0,    0,    0,    0,    0,  212,
      213,  213,    0,    0,  213,  213,  213,  214,  214,    0,
      214,  214,    0,  214,  215,  215,    0,  215,  215,    0,
      215,  216,  216,    0,  216,  216,  216,  216,  217,  217,

      217,  217,  217,  217,  217,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
#define INITIAL 0
#define IFILE 1
#define CODEBLOCK 2
#define COMMENT 3

#line 5 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
#include <stdlib.h>
#include <string.h>
#include "idlcpp.y.h"
#include "yyfuncs.h"

YY_BUFFER_STATE createBufferState(FILE* file);
int yytokenno = 0;
int yycolumnno = 1;
#line 655 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"


#line 809 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 606 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 17 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{BEGIN IFILE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{
						{
							int c;
							while((c = input()) && c != '\n')
							{}
							addSourceFile(yytext);
							yycolumnno = 0;
							BEGIN INITIAL;
						}
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{fprintf(stderr, "%d bad import line\n", yylineno); yyterminate();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN CODEBLOCK;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1; yytokenno++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno++; yytokenno++;}
	YY_BREAK
case YY_STATE_EOF(CODEBLOCK):
#line 35 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{unterminatedCode();yyterminate();}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN COMMENT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno += strlen(yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno = 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yycolumnno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 42 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{unterminatedComment();yyterminate();}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 48 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yyterminate();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext + 2); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext + 1); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 17:
#line 55 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 18:
#line 56 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 19:
#line 57 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 20:
#line 58 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 21:
#line 59 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 22:
#line 60 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 23:
#line 61 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 24:
#line 62 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
case 25:
YY_RULE_SETUP
#line 62 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(yytext[0]); yycolumnno++; yytokenno++; return yytext[0];}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(yytext[0]);				yycolumnno += strlen(yytext); yytokenno++; return LTS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(yytext[0]);				yycolumnno += strlen(yytext); yytokenno++; return GTS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_scope);		yycolumnno += strlen(yytext); yytokenno++; return SCOPE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_bool);		yycolumnno += strlen(yytext); yytokenno++; return BOOL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_char);		yycolumnno += strlen(yytext); yytokenno++; return CHAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_wchar_t);		yycolumnno += strlen(yytext); yytokenno++; return WCHAR_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_short);		yycolumnno += strlen(yytext); yytokenno++; return SHORT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_long);		yycolumnno += strlen(yytext); yytokenno++; return LONG;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_int);			yycolumnno += strlen(yytext); yytokenno++; return INT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_signed);		yycolumnno += strlen(yytext); yytokenno++; return SIGNED;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_unsigned);	yycolumnno += strlen(yytext); yytokenno++; return UNSIGNED;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_float);		yycolumnno += strlen(yytext); yytokenno++; return FLOAT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_double);		yycolumnno += strlen(yytext); yytokenno++; return DOUBLE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_void);		yycolumnno += strlen(yytext); yytokenno++; return VOID;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_ref);			yycolumnno += strlen(yytext); yytokenno++; return REF;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_ptr);			yycolumnno += strlen(yytext); yytokenno++; return PTR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_new);			yycolumnno += strlen(yytext); yytokenno++; return NEW;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_abstract);	yycolumnno += strlen(yytext); yytokenno++; return ABSTRACT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_namespace);	yycolumnno += strlen(yytext); yytokenno++; return NAMESPACE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_enum);		yycolumnno += strlen(yytext); yytokenno++; return ENUM;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_class);		yycolumnno += strlen(yytext); yytokenno++; return CLASS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_struct);		yycolumnno += strlen(yytext); yytokenno++; return STRUCT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_virtual);		yycolumnno += strlen(yytext); yytokenno++; return VIRTUAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_static);		yycolumnno += strlen(yytext); yytokenno++; return STATIC;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_const);		yycolumnno += strlen(yytext); yytokenno++; return CONST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_typedef);		yycolumnno += strlen(yytext); yytokenno++; return TYPEDEF;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_primitive);	yycolumnno += strlen(yytext); yytokenno++; return PRIMITIVE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_get);			yycolumnno += strlen(yytext); yytokenno++; return GET;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_set);			yycolumnno += strlen(yytext); yytokenno++; return SET;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_nocode);		yycolumnno += strlen(yytext); yytokenno++; return NOCODE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_nometa);		yycolumnno += strlen(yytext); yytokenno++; return NOMETA;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_export);		yycolumnno += strlen(yytext); yytokenno++; return EXPORT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newToken(snt_keyword_override);	yycolumnno += strlen(yytext); yytokenno++; return OVERRIDE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{yylval.sn = newIdentify(yytext);		yycolumnno += strlen(yytext); yytokenno++; return IDENTIFY;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{++yycolumnno;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1218 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 206);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 106 "D:\\GitHub\\idlcpp\\idlcpp\\src\\idlcpp.l"


YY_BUFFER_STATE createBufferState(FILE* file)
{
	YY_BUFFER_STATE bs;
	bs = yy_create_buffer(file, YY_BUF_SIZE);
	return bs;
}