//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

#include "./Reference.h"
#include "./Metadata.h"
#include "./Type.h"
namespace pafcore{ class ClassType; }

namespace pafcore
{

	class PAFCORE_EXPORT InstanceField : public Metadata
	{
	public:
		static ::pafcore::ClassType* GetType();
		virtual ::pafcore::ClassType* getType();
		virtual size_t getAddress();

		Type* get_type();
		ClassType* get_objectType();
		size_t get_offset();
		bool get_isArray();
		bool get_isPointer();
		bool get_isConstant();

	public:
		InstanceField(const char* name, ClassType* objectType, Type* type, size_t offset, size_t arraySize, bool constant, TypeCompound tc);
	public:
		bool isArray()
		{
			return tc_array == m_typeCompound;
		}
		bool isPointer()
		{
			return tc_pointer == m_typeCompound;
		}
		bool isConstant()
		{
			return m_constant;
		}
	public:
		Type* m_type;
		ClassType* m_objectType;
		size_t m_offset;
		size_t m_arraySize;
		bool m_constant;
		byte_t m_typeCompound;

	};

}