//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

#include "./Reference.h"
namespace pafcore{ class ClassType; }

namespace pafcore
{
	class PAFCORE_EXPORT Object : public Reference
	{
	public:
		static ::pafcore::ClassType* GetType();
		virtual ::pafcore::ClassType* getType();
		virtual size_t getAddress();


	public:
		virtual bool serializable() const
		{
			return true;
		}

	};
}