//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

#include "./Metadata.h"
namespace pafcore{ class Type; }
namespace pafcore{ class ClassType; }

namespace pafcore
{
	class PAFCORE_EXPORT TypeAlias : public Metadata
	{
	public:
		static ::pafcore::ClassType* GetType();
		virtual ::pafcore::ClassType* getType();
		virtual size_t getAddress();

		Type* get_type() const;

	public:
		TypeAlias(const char* name, Type* type, const char* declarationFile);
		~TypeAlias();
	public:
		const char* getDeclarationFile() const;
	public:
		Type* m_type;
		Metadata* m_enclosing;
		const char* m_declarationFile;//类型声明所在文件路径

	};


	inline const char* TypeAlias::getDeclarationFile() const
	{
		return m_declarationFile;
	}


}