//DO NOT EDIT THIS FILE, it is generated by idlcpp
//aifeng_peng@hotmail.com

#pragma once

#include "./Metadata.h"
namespace pafcore{ class Type; }

namespace pafcore
{
	class PAFCORE_EXPORT TypeAlias : public Metadata
	{
	public:
		virtual ::pafcore::Type* getType();

		Type* get_type();

	public:
		TypeAlias(const char* name, Type* type);
	public:
		Type* m_type;
		
	};

}