#line 1 "D:/idlcpp/src/idlcpp.l.c"

#line 3 "D:/idlcpp/src/idlcpp.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[277] =
    {   0,
       98,   98,    0,    0,    0,    0,    0,    0,  101,   98,
       96,   97,   99,   26,   99,   98,   99,   21,   23,   34,
       35,   19,   17,   36,   18,   20,   38,   37,   28,   27,
       29,   39,   93,   32,   33,   22,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   30,   24,   31,   25,    2,    3,    6,    7,
        8,    8,   11,   12,   13,   13,   98,   97,   54,    0,
       94,   15,   16,   16,    4,   45,   57,   47,   43,   59,
       41,   60,   42,    9,    0,   44,   40,   49,   55,   53,
       56,   50,   93,   46,   93,   93,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   48,   58,    2,    6,    7,    5,   11,
       12,   10,   15,   15,   16,    0,   14,   51,   52,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       84,   66,   93,   93,   93,   93,   93,   93,   85,   93,
       93,   93,   93,   93,   93,    0,   93,   93,   93,   93,
       16,   93,   61,   93,   62,   93,   93,   93,   93,   75,
       93,   93,   65,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,    0,   95,   93,   93,   71,

       93,   16,   93,   93,   76,   80,   93,   93,   93,   69,
       93,   93,   93,   93,   93,   64,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   16,   93,   93,   93,
       70,   89,   93,   87,   88,   93,   93,   67,   79,   93,
       77,   93,   93,   93,   93,   93,   93,   16,   93,   93,
       93,   93,   93,   93,   93,   93,   82,   93,   93,   78,
       63,    0,    1,   73,   93,   92,   93,   81,   90,   72,
       91,   83,   68,   86,   74,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,    1,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   19,   18,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,    1,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   26,   40,   41,   42,
       43,   44,   26,   45,   46,   47,   48,   49,   50,   51,
       52,   26,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    2,    3,    4,    2,    5,    6,    2,    2,    2,
        2,    2,    7,    2,    2,    2,    2,    1,    1,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    2,    2,    2
    } ;

static const flex_int16_t yy_base[290] =
    {   0,
        0,    0,   54,   55,   59,   61,   66,   68,  340,    0,
      857,  857,  332,  300,  285,   66,  857,  248,   64,  857,
      857,  247,   61,  857,   60,   65,  240,  857,   63,  161,
       66,  857,   90,  857,  857,  158,   91,   92,   93,   94,
      101,  102,  103,  105,  106,  110,  113,  120,  121,  144,
      125,  133,  857,   92,  857,  857,    0,  857,    0,  857,
      158,  105,    0,  857,  136,  113,    0,  857,  857,  119,
      857,  186,  242,  243,  857,  857,  857,  857,  857,  857,
      857,  857,  857,  857,  115,  857,  857,   93,  857,  857,
      857,   73,  143,  857,  244,  245,  147,  246,  247,  255,

      254,  256,  257,  258,  265,  266,  267,  268,  275,  278,
      280,  282,  279,  291,  292,  299,  300,  302,  164,  311,
      320,  321,  324,  857,  857,    0,    0,  857,  857,    0,
      857,  857,    0,    0,  331,   77,  857,  857,  857,  332,
      336,  335,  344,  346,  347,  348,  349,  357,  360,  365,
      168,  171,  367,  370,  379,  381,  384,  393,  173,  394,
      401,  405,  406,  413,  414,   71,  416,  417,  424,  425,
      426,  427,  175,  429,  176,  434,  439,  441,  443,  178,
      446,  458,  459,  460,  469,  470,  480,  481,  483,  488,
      492,  491,  495,  500,  493,   53,  857,  507,  503,  508,

      511,  512,  515,  535,  531,  536,  540,  538,  547,  548,
      551,  552,  559,  560,  561,  563,  571,  573,  574,  575,
      578,  582,  585,  590,  592,  595,  597,  607,  611,  612,
      614,  619,  623,  626,  627,  628,  630,  638,  640,  642,
      645,  650,  654,  655,  659,  662,  666,  673,  669,  676,
      677,  681,  680,  684,  685,  692,  688,  699,  697,  700,
      702,  318,  857,  704,  714,  717,  721,  728,  729,  732,
      736,  737,  739,  740,  741,  857,  756,  764,  772,  780,
      786,  794,  802,  808,  816,  824,  832,  840,  848
    } ;

static const flex_int16_t yy_def[290] =
    {   0,
      276,    1,  277,  277,  278,  278,  279,  279,  276,  280,
      276,  276,  276,  276,  281,  282,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  283,  276,  276,  276,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  276,  276,  276,  276,  284,  276,  285,  276,
      276,  276,  286,  276,  276,  276,  280,  276,  276,  281,
      276,  276,  282,  282,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  287,  276,  276,  276,  276,  276,
      276,  276,  283,  276,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  276,  276,  284,  285,  276,  276,  286,
      276,  276,   72,  288,  282,  287,  276,  276,  276,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  289,  283,  283,  283,  283,
      282,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  289,  276,  283,  283,  283,

      283,  282,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  282,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  282,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  276,  276,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,    0,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276
    } ;

static const flex_int16_t yy_nxt[914] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   10,   10,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   33,
       37,   38,   39,   40,   41,   42,   43,   33,   44,   45,
       33,   46,   47,   33,   33,   48,   49,   50,   51,   52,
       33,   33,   53,   54,   55,   56,   58,   58,  197,   58,
       58,   60,   61,   60,   61,   62,   67,   62,   64,   65,
       64,   65,   72,   77,   80,   82,  197,   84,   66,  137,
       66,   85,   83,   81,   88,   89,   78,   86,   91,   92,
       67,   67,   67,   67,   67,  139,   67,   67,   67,   67,

       67,   67,   67,   67,   74,   67,   67,   67,   67,   67,
       67,   67,   67,   67,  124,  138,   67,  137,   75,   67,
       67,   67,   95,   97,   71,   67,   67,   67,  101,  132,
       98,   67,   99,   67,   96,  100,  102,  106,  131,   67,
      109,  105,  103,   67,   67,  125,  107,   67,  108,   67,
       67,  104,  110,   67,  113,  117,  111,  114,  115,  129,
      128,  112,  119,  121,   67,  123,  116,  122,   67,  166,
       67,   67,  118,   67,   67,   67,   67,   67,   67,   67,
       94,   67,   67,   90,   67,  120,  133,  134,  142,  134,
      134,  134,  133,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  133,  133,  134,  134,  134,  134,  134,
      134,  133,  134,  134,  134,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  134,  134,
      134,  134,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   87,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   79,
       76,   67,   67,   67,   67,   67,  143,  144,   67,   67,
       67,   67,   67,  135,   67,   67,   67,  141,   67,  140,
       71,   67,   67,  146,  276,  276,  145,   67,   67,   67,

       67,  149,   67,  147,  148,   67,   67,  150,   67,  153,
      155,   67,  151,  152,  157,  154,  158,   67,  156,  262,
       67,   67,   69,  263,   67,  159,   67,   67,  161,  162,
       67,   67,   67,  160,   68,   67,   67,   67,   67,  276,
      164,   67,   67,  163,   67,  165,   67,   67,   67,   67,
       67,  276,   67,   67,   67,   67,  167,   67,  276,  169,
       67,  170,  276,   67,  168,   67,   67,   67,  174,  276,
       67,   67,  276,   67,  171,  173,   67,  276,  172,   67,
      179,   67,  178,  276,   67,   67,  276,   67,  175,  276,
       67,  176,  177,   67,   67,  182,  276,  180,  276,   67,

       67,   67,  181,  183,  184,   67,   67,   67,  276,  276,
      276,   67,   67,   67,   67,  186,   67,   67,  276,   67,
       67,  185,   67,   67,   67,   67,   67,   67,  187,   67,
       67,   67,   67,   67,   67,   67,  276,  188,  189,   67,
       67,   67,  190,   67,  192,   67,   67,   67,  195,   67,
      276,  191,   67,  193,  198,  201,  194,  200,   67,   67,
       67,  276,  276,  199,   67,   67,   67,  204,  202,   67,
       67,  203,  276,  276,  276,   67,   67,  207,  276,  205,
       67,   67,  208,   67,  276,  206,   67,   67,   67,   67,
      209,   67,   67,   67,   67,   67,  276,   67,   67,   67,

       67,   67,  212,   67,  210,  211,   67,   67,   67,   67,
      214,   67,   67,   67,   67,   67,  213,   67,   67,  276,
      276,   67,  217,  276,  276,  215,  222,  220,  276,  216,
      218,   67,  219,  276,  223,   67,   67,   67,   67,  221,
       67,   67,   67,  224,   67,  228,   67,   67,   67,  276,
      225,   67,   67,   67,   67,  226,  227,   67,   67,   67,
       67,   67,  276,   67,  276,   67,   67,   67,  229,   67,
      230,   67,  231,   67,   67,   67,  276,   67,   67,   67,
       67,   67,   67,  276,   67,   67,  234,  276,   67,  235,
       67,   67,   67,  232,  233,   67,   67,   67,   67,  237,

      276,   67,  276,   67,  238,  239,  236,   67,  242,  276,
      240,   67,   67,   67,   67,  244,  243,   67,   67,   67,
       67,  241,  246,   67,  247,   67,   67,   67,   67,   67,
       67,  245,   67,   67,   67,  276,   67,  276,   67,  249,
       67,  250,   67,  248,   67,   67,   67,  276,   67,  276,
       67,   67,  276,  252,   67,   67,   67,  276,  251,   67,
       67,   67,   67,  254,  276,   67,   67,  276,   67,   67,
      253,  255,   67,   67,  262,   67,   67,   67,  263,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,  257,
       67,   67,   67,  259,   67,  258,  256,   67,   67,   67,

       67,  260,   67,   67,   67,   67,   67,  276,   67,  276,
       67,  266,  261,  267,   67,  264,  276,   67,  269,  276,
       67,   67,  265,   67,  268,  276,  271,   67,   67,   67,
      273,  270,   67,  272,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,  276,   67,   67,   67,  274,  276,
      276,  276,  276,  276,  276,  275,   57,   57,   57,   57,
       57,   57,   57,   57,   59,   59,   59,   59,   59,   59,
       59,   59,   63,   63,   63,   63,   63,   63,   63,   63,
       67,  276,  276,  276,  276,   67,   70,   70,   70,   70,
       70,   70,   70,   70,   73,  276,  276,  276,  276,   73,

      276,   73,   93,  276,  276,  276,  276,   93,  126,  126,
      276,  126,  276,  126,  126,  126,  127,  127,  276,  276,
      127,  276,  127,  127,  130,  130,  276,  276,  130,  130,
      276,  130,  136,  136,  136,  136,  136,  136,  136,  136,
      134,  134,  276,  134,  134,  134,  134,  134,  196,  196,
      196,  196,  196,  196,  196,  196,    9,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276
    } ;

static const flex_int16_t yy_chk[914] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,  196,    3,
        4,    5,    5,    6,    6,    5,   16,    6,    7,    7,
        8,    8,   16,   19,   23,   25,  166,   26,    7,  136,
        8,   26,   25,   23,   29,   29,   19,   26,   31,   31,
       33,   37,   38,   39,   40,   92,   33,   37,   38,   39,

       40,   41,   42,   43,   16,   44,   45,   41,   42,   43,
       46,   44,   45,   47,   54,   88,   46,   85,   16,   47,
       48,   49,   37,   39,   70,   51,   48,   49,   40,   66,
       39,   51,   39,   52,   38,   39,   40,   43,   65,   52,
       46,   42,   41,   93,   50,   54,   44,   97,   45,   93,
       50,   41,   46,   97,   48,   49,   47,   48,   48,   62,
       61,   47,   50,   51,  119,   52,   48,   51,  151,  119,
      119,  152,   49,  159,  151,  173,  175,  152,  180,  159,
       36,  173,  175,   30,  180,   50,   72,   72,   97,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   73,   74,   95,   96,   98,   99,   73,   74,
       95,   96,   98,   99,  101,  100,  102,  103,  104,   27,
      101,  100,  102,  103,  104,  105,  106,  107,  108,   22,
       18,  105,  106,  107,  108,  109,   98,   99,  110,  113,
      111,  109,  112,   74,  110,  113,  111,   96,  112,   95,
       15,  114,  115,  101,   73,   74,  100,  114,  115,  116,

      117,  104,  118,  102,  103,  116,  117,  105,  118,  108,
      110,  120,  106,  107,  111,  109,  112,  120,  110,  262,
      121,  122,   14,  262,  123,  113,  121,  122,  115,  116,
      123,  135,  140,  114,   13,  142,  141,  135,  140,    9,
      117,  142,  141,  116,  143,  118,  144,  145,  146,  147,
      143,    0,  144,  145,  146,  147,  120,  148,    0,  122,
      149,  123,    0,  148,  121,  150,  149,  153,  142,    0,
      154,  150,    0,  153,  135,  141,  154,    0,  140,  155,
      147,  156,  146,  135,  157,  155,    0,  156,  143,    0,
      157,  144,  145,  158,  160,  150,    0,  148,    0,  158,

      160,  161,  149,  153,  154,  162,  163,  161,    0,    0,
        0,  162,  163,  164,  165,  156,  167,  168,    0,  164,
      165,  155,  167,  168,  169,  170,  171,  172,  157,  174,
      169,  170,  171,  172,  176,  174,    0,  158,  160,  177,
      176,  178,  161,  179,  163,  177,  181,  178,  165,  179,
        0,  162,  181,  163,  167,  170,  164,  169,  182,  183,
      184,    0,    0,  168,  182,  183,  184,  174,  171,  185,
      186,  172,    0,    0,    0,  185,  186,  178,  171,  176,
      187,  188,  179,  189,    0,  177,  187,  188,  190,  189,
      181,  192,  191,  195,  190,  193,    0,  192,  191,  195,

      194,  193,  185,  199,  182,  184,  194,  198,  200,  199,
      187,  201,  202,  198,  200,  203,  186,  201,  202,    0,
        0,  203,  190,    0,    0,  188,  195,  193,    0,  189,
      191,  205,  192,    0,  195,  204,  206,  205,  208,  194,
      207,  204,  206,  198,  208,  203,  207,  209,  210,    0,
      199,  211,  212,  209,  210,  201,  202,  211,  212,  213,
      214,  215,    0,  216,  202,  213,  214,  215,  204,  216,
      207,  217,  208,  218,  219,  220,    0,  217,  221,  218,
      219,  220,  222,    0,  221,  223,  212,    0,  222,  213,
      224,  223,  225,  209,  211,  226,  224,  227,  225,  215,

        0,  226,    0,  227,  217,  218,  214,  228,  221,    0,
      219,  229,  230,  228,  231,  223,  222,  229,  230,  232,
      231,  220,  225,  233,  226,  232,  234,  235,  236,  233,
      237,  224,  234,  235,  236,    0,  237,    0,  238,  228,
      239,  229,  240,  227,  238,  241,  239,    0,  240,  227,
      242,  241,    0,  233,  243,  244,  242,    0,  230,  245,
      243,  244,  246,  237,    0,  245,  247,    0,  246,  249,
      236,  240,  247,  248,  248,  249,  250,  251,  248,  248,
      253,  252,  250,  251,  254,  255,  253,  252,  257,  243,
      254,  255,  256,  245,  257,  244,  242,  259,  256,  258,

      260,  246,  261,  259,  264,  258,  260,    0,  261,    0,
      264,  251,  247,  252,  265,  249,    0,  266,  254,    0,
      265,  267,  250,  266,  253,  248,  256,  267,  268,  269,
      259,  255,  270,  258,  268,  269,  271,  272,  270,  273,
      274,  275,  271,  272,    0,  273,  274,  275,  265,    0,
        0,    0,    0,    0,    0,  267,  277,  277,  277,  277,
      277,  277,  277,  277,  278,  278,  278,  278,  278,  278,
      278,  278,  279,  279,  279,  279,  279,  279,  279,  279,
      280,    0,    0,    0,    0,  280,  281,  281,  281,  281,
      281,  281,  281,  281,  282,    0,    0,    0,    0,  282,

        0,  282,  283,    0,    0,    0,    0,  283,  284,  284,
        0,  284,    0,  284,  284,  284,  285,  285,    0,    0,
      285,    0,  285,  285,  286,  286,    0,    0,  286,  286,
        0,  286,  287,  287,  287,  287,  287,  287,  287,  287,
      288,  288,    0,  288,  288,  288,  288,  288,  289,  289,
      289,  289,  289,  289,  289,  289,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[101] =
    {   0,
0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "D:/idlcpp/src/idlcpp.l"
#define YY_NO_UNISTD_H 1

#line 5 "D:/idlcpp/src/idlcpp.l"
#include <stdlib.h>
#include <string.h>
#include "idlcpp.y.h"
#include "yyfuncs.h"

YY_BUFFER_STATE createBufferState(FILE* file);
int yytokenno = 0;
int yycolumnno = 1;
int yyHasArrayProperty = 0;
int yyHasListProperty = 0;
int yyHasMapProperty = 0;
int yyHasDelegate = 0;
#line 782 "D:/idlcpp/src/idlcpp.l.c"
#line 783 "D:/idlcpp/src/idlcpp.l.c"

#define INITIAL 0
#define IFILE 1
#define CODEBLOCK 2
#define COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "D:/idlcpp/src/idlcpp.l"


#line 1006 "D:/idlcpp/src/idlcpp.l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 276 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "D:/idlcpp/src/idlcpp.l"
{BEGIN IFILE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "D:/idlcpp/src/idlcpp.l"
{
						{
							int c;
							while((c = input()) && c != '\n')
							{}
							addSourceFile(yytext);
							yycolumnno = 0;
							BEGIN INITIAL;
						}
					}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 32 "D:/idlcpp/src/idlcpp.l"
{fprintf(stderr, "%d bad import line\n", yylineno); yyterminate();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "D:/idlcpp/src/idlcpp.l"
{yycolumnno += 2; BEGIN CODEBLOCK;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "D:/idlcpp/src/idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 37 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1; yytokenno++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext); yycolumnno++; yytokenno++;}
	YY_BREAK
case YY_STATE_EOF(CODEBLOCK):
#line 39 "D:/idlcpp/src/idlcpp.l"
{unterminatedCode();yyterminate();}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "D:/idlcpp/src/idlcpp.l"
{yycolumnno += 2; BEGIN COMMENT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "D:/idlcpp/src/idlcpp.l"
{yycolumnno += 2; BEGIN INITIAL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "D:/idlcpp/src/idlcpp.l"
{yycolumnno += strlen(yytext); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 44 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock("\n"); yycolumnno = 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "D:/idlcpp/src/idlcpp.l"
{yycolumnno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 46 "D:/idlcpp/src/idlcpp.l"
{unterminatedComment();yyterminate();}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 50 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock("\n"); yycolumnno = 1;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 52 "D:/idlcpp/src/idlcpp.l"
{yyterminate();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext + 2); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext + 1); yycolumnno += strlen(yytext); yytokenno++;}
	YY_BREAK
case 17:
#line 59 "D:/idlcpp/src/idlcpp.l"
case 18:
#line 60 "D:/idlcpp/src/idlcpp.l"
case 19:
#line 61 "D:/idlcpp/src/idlcpp.l"
case 20:
#line 62 "D:/idlcpp/src/idlcpp.l"
case 21:
#line 63 "D:/idlcpp/src/idlcpp.l"
case 22:
#line 64 "D:/idlcpp/src/idlcpp.l"
case 23:
#line 65 "D:/idlcpp/src/idlcpp.l"
case 24:
#line 66 "D:/idlcpp/src/idlcpp.l"
case 25:
#line 67 "D:/idlcpp/src/idlcpp.l"
case 26:
#line 68 "D:/idlcpp/src/idlcpp.l"
case 27:
#line 69 "D:/idlcpp/src/idlcpp.l"
case 28:
#line 70 "D:/idlcpp/src/idlcpp.l"
case 29:
#line 71 "D:/idlcpp/src/idlcpp.l"
case 30:
#line 72 "D:/idlcpp/src/idlcpp.l"
case 31:
#line 73 "D:/idlcpp/src/idlcpp.l"
case 32:
#line 74 "D:/idlcpp/src/idlcpp.l"
case 33:
#line 75 "D:/idlcpp/src/idlcpp.l"
case 34:
#line 76 "D:/idlcpp/src/idlcpp.l"
case 35:
#line 77 "D:/idlcpp/src/idlcpp.l"
case 36:
#line 78 "D:/idlcpp/src/idlcpp.l"
case 37:
#line 79 "D:/idlcpp/src/idlcpp.l"
case 38:
#line 80 "D:/idlcpp/src/idlcpp.l"
case 39:
YY_RULE_SETUP
#line 80 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(yytext[0]);				yycolumnno++; yytokenno++; return yytext[0];}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_scope);					yycolumnno += strlen(yytext); yytokenno++; return SCOPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_add_assign);				yycolumnno += strlen(yytext); yytokenno++; return ADD_ASSIGN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_sub_assign);				yycolumnno += strlen(yytext); yytokenno++; return SUB_ASSIGN;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_mul_assign);				yycolumnno += strlen(yytext); yytokenno++; return MUL_ASSIGN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_div_assign);				yycolumnno += strlen(yytext); yytokenno++; return DIV_ASSIGN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_mod_assign);				yycolumnno += strlen(yytext); yytokenno++; return MOD_ASSIGN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_xor_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_XOR_ASSIGN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_and_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_AND_ASSIGN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_bit_or_assign);			yycolumnno += strlen(yytext); yytokenno++; return BIT_OR_ASSIGN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_left_shift);				yycolumnno += strlen(yytext); yytokenno++; return LEFT_SHIFT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_right_shift);			yycolumnno += strlen(yytext); yytokenno++; return RIGHT_SHIFT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_left_shift_assign);		yycolumnno += strlen(yytext); yytokenno++; return LEFT_SHIFT_ASSIGN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_right_shift_assign);		yycolumnno += strlen(yytext); yytokenno++; return RIGHT_SHIFT_ASSIGN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_equal);					yycolumnno += strlen(yytext); yytokenno++; return EQUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_not_equal);				yycolumnno += strlen(yytext); yytokenno++; return NOT_EQUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_less_equal);				yycolumnno += strlen(yytext); yytokenno++; return LESS_EQUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_greater_equal);			yycolumnno += strlen(yytext); yytokenno++; return GREATER_EQUAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_and);					yycolumnno += strlen(yytext); yytokenno++; return AND;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_or);						yycolumnno += strlen(yytext); yytokenno++; return OR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_inc);					yycolumnno += strlen(yytext); yytokenno++; return INC;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_operator_dec);					yycolumnno += strlen(yytext); yytokenno++; return DEC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_bool);					yycolumnno += strlen(yytext); yytokenno++; return BOOL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_char);					yycolumnno += strlen(yytext); yytokenno++; return CHAR;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_wchar_t);					yycolumnno += strlen(yytext); yytokenno++; return WCHAR_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_short);					yycolumnno += strlen(yytext); yytokenno++; return SHORT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_long);					yycolumnno += strlen(yytext); yytokenno++; return LONG;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_int);						yycolumnno += strlen(yytext); yytokenno++; return INT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_signed);					yycolumnno += strlen(yytext); yytokenno++; return SIGNED;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_unsigned);				yycolumnno += strlen(yytext); yytokenno++; return UNSIGNED;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_float);					yycolumnno += strlen(yytext); yytokenno++; return FLOAT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_double);					yycolumnno += strlen(yytext); yytokenno++; return DOUBLE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_void);					yycolumnno += strlen(yytext); yytokenno++; return VOID;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_string_t);				yycolumnno += strlen(yytext); yytokenno++; return STRING_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_abstract);				yycolumnno += strlen(yytext); yytokenno++; return ABSTRACT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_namespace);				yycolumnno += strlen(yytext); yytokenno++; return NAMESPACE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_enum);					yycolumnno += strlen(yytext); yytokenno++; return ENUM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_class);					yycolumnno += strlen(yytext); yytokenno++; return CLASS;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_struct);					yycolumnno += strlen(yytext); yytokenno++; return STRUCT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_virtual);					yycolumnno += strlen(yytext); yytokenno++; return VIRTUAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_static);					yycolumnno += strlen(yytext); yytokenno++; return STATIC;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_const);					yycolumnno += strlen(yytext); yytokenno++; return CONST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_operator);				yycolumnno += strlen(yytext); yytokenno++; return OPERATOR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_typedef);					yycolumnno += strlen(yytext); yytokenno++; return TYPEDEF;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_typename);				yycolumnno += strlen(yytext); yytokenno++; return TYPENAME;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_get);						yycolumnno += strlen(yytext); yytokenno++; return GET;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_set);						yycolumnno += strlen(yytext); yytokenno++; return SET;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_candidate);				yycolumnno += strlen(yytext); yytokenno++; return CANDIDATE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_nocode);					yycolumnno += strlen(yytext); yytokenno++; return NOCODE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_nometa);					yycolumnno += strlen(yytext); yytokenno++; return NOMETA;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_export);					yycolumnno += strlen(yytext); yytokenno++; return EXPORT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_override);				yycolumnno += strlen(yytext); yytokenno++; return OVERRIDE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_template);				yycolumnno += strlen(yytext); yytokenno++; return TEMPLATE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newToken(snt_keyword_delegate);				yycolumnno += strlen(yytext); yytokenno++; return DELEGATE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newIdentify(yytext);					yycolumnno += strlen(yytext); yytokenno++; return IDENTIFY;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 140 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newString(yytext + 1);					yycolumnno += strlen(yytext); yytokenno++; return STRING;}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 141 "D:/idlcpp/src/idlcpp.l"
{yylval.sn = newString(yytext + 3);					yycolumnno += strlen(yytext); yytokenno++; return U8STRING;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 143 "D:/idlcpp/src/idlcpp.l"
{++yycolumnno;}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 144 "D:/idlcpp/src/idlcpp.l"
{newCodeBlock(yytext); yycolumnno = 1;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 146 "D:/idlcpp/src/idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 147 "D:/idlcpp/src/idlcpp.l"
{invalidString(yytext); yycolumnno += strlen(yytext);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 149 "D:/idlcpp/src/idlcpp.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1532 "D:/idlcpp/src/idlcpp.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 276);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "D:/idlcpp/src/idlcpp.l"


YY_BUFFER_STATE createBufferState(FILE* file)
{
	YY_BUFFER_STATE bs;
	bs = yy_create_buffer(file, YY_BUF_SIZE);
	return bs;
}
